### ISSUE TITLE
simditor-uploader-button.js:49 Uncaught TypeError: Cannot read property 'opts' of undefined

### ISSUE THREAD

**Issue by msterzhang** [usho-sosho/simditor-uploader-button#1]
<script src="{% static "xadmin/simditor/module.js" %}"></script>
    <script src="{% static "xadmin/simditor/hotkeys.js" %}"></script>
    <script src="{% static "xadmin/simditor/uploader.js" %}"></script>
    <script src="https://cdn.bootcss.com/marked/0.3.12/marked.js"></script>
    <script src="https://cdn.bootcss.com/js-beautify/1.7.5/beautify-html.js"></script>
    <script src="https://cdn.bootcss.com/simditor/2.3.23/lib/simditor.js"></script>
    <script src="https://cdn.bootcss.com/to-markdown/3.1.1/to-markdown.js"></script>
    <script src="{% static "xadmin/simditor/simditor-markdown.js" %}"></script>

    <script src="{% static "xadmin/simditor/simditor-html.js" %}"></script>
    <script src="{% static "xadmin/simditor/simditor-fullscreen.js" %}"></script>
    <script src="{% static "xadmin/simditor/simditor-uploader-button.js" %}"></script>
    <script src="{% static "xadmin/simditor/simditor-video.js" %}"></script>

**Comment by yujingwyh** [comment]
这是因为你没有开启uploader，也就是没有设置simditor配置中upload字段，可以看一下示例，也可以点击查看官方示例[链接](https://simditor.tower.im/docs/doc-config.html#anchor-upload)
`
new Simditor({
            textarea: $('#txt-content'),
            placeholder: '这里输入文字...',
            toolbar: toolbar,
            pasteImage: true,
            defaultImage: 'assets/images/image.png',
            video: {
                size:50
            },
           upload: {
            connectionCount:3000,
            url: '/editor/php/control.php'
           }
        });
`

**Comment by msterzhang** [comment]
嗦嘎  谢谢啦 我再研究研究
